[package]
name = "wait-service"
version = "0.4.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/magiclen/wait-service"
homepage = "https://magiclen.org/wait-service"
keywords = ["wait-for-it", "tcp", "unix", "socket", "uds"]
categories = ["command-line-utilities"]
description = "Wait Service is a pure rust program to test and wait on the availability of multiple services."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
clap = { version = "4.0.17", features = ["derive"] }
concat-with = "0.2"
terminal_size = "0.4"

anyhow = "1.0.46"

tokio = { version = "1.45", features = ["rt", "time", "net", "macros"] }

dnsclient = { version = "0.2", default-features = false, features = ["async-tokio"] }

serde = { version = "1.0.113", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

path-absolutize = { version = "4", features = ["fixed_workdir"] }

[features]
json = ["dep:serde", "dep:serde_json", "tokio/fs"]
