[package]
name = "wait-service"
version = "0.1.1"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2021"
repository = "https://github.com/magiclen/wait-service"
homepage = "https://magiclen.org/wait-service"
keywords = ["wait-for-it", "tcp", "unix", "socket", "uds"]
categories = ["command-line-utilities"]
description = "Wait Service is a pure rust program to test and wait on the availability of a service."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
clap = "2.33.3"
concat-with = "0.2"
terminal_size = "0.1"

tokio = { version = "1.12", features = ["rt", "time", "net", "macros"] }
